functional:
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться в системе.
  - Вход в игру возможен через учетную запись GitHub.
  - Пользователь может создать игру или присоединиться к существующей.
  - Игра может быть создана как приватная, доступная только по ссылке, или публичная.
  - В игре участвуют два игрока, каждый из которых получает одинаковое задание на программирование.
  - После начала игры оба игрока получают одинаковую задачу.
  - Игроки должны написать и отправить решение задачи в виде кода.
  - Система должна автоматически проверять решение на корректность, используя набор тестов.
  - Побеждает игрок, который первым корректно решит задачу.
  - В случае, если оба игрока не могут решить задачу за установленное время, игра завершается ничьей.
  - Система должна отображать таблицу лидеров с результатами игр.
  - Таблица лидеров должна показывать количество побед, поражений и ничьих каждого игрока.
  - Система должна предоставить игрокам возможность использовать подсказки, если такие предусмотрены игрой.
  - Пользователи получают рейтинг на основе своих побед и поражений.
  - Игроки могут повышать свой уровень, набирая очки рейтинга.
  - В процессе игры пользователи должны иметь возможность общаться друг с другом в чате.
  - Чат должен поддерживать отправку текстовых сообщений в реальном времени.

non-functional:
  - Игра должна загружаться и работать без значительных задержек на стандартных интернет-соединениях.
  - Проверка решений должна происходить в реальном времени с минимальной задержкой.
  - Система должна поддерживать одновременное участие большого количества пользователей без значительного снижения производительности.
  - Система должна обеспечивать защиту учетных данных пользователей.
  - Должны быть предусмотрены механизмы для предотвращения мошенничества и нечестной игры.
  - Игра должна быть доступна 99.9% времени, сбои должны быть минимальными.
  - Интерфейс должен быть интуитивно понятным и удобным для пользователя.
  - Интерфейс должен поддерживать несколько языков.
  - Игра должна корректно работать на различных устройствах и в разных браузерах.

implicit:
  - Пользователи ожидают наличия возможностей для социального взаимодействия, таких как обмен сообщениями, просмотр профилей других игроков, добавление в друзья.
  - Игроки ожидают наличия механик, которые будут мотивировать их играть чаще, такие как награды за достижение определенных целей, ежедневные задания и так далее.
  - Пользователи ожидают оперативной обратной связи от системы в случае успешного или неуспешного выполнения задач, что подразумевает наличие визуальных и звуковых индикаторов.
  - Новые пользователи ожидают, что им будет легко понять, как начать игру, не читая обширных инструкций.
