functional:
  - Пользователь должен иметь возможность регистрации и авторизации в системе.
  - Пользователи могут участвовать в соревновательных матчах по программированию.
  - Каждый матч должен иметь таймер для отслеживания оставшегося времени.
  - Должен быть доступен рейтинг пользователей, обновляемый после каждого матча.
  - Реализовать систему задач с различными уровнями сложности.
  - Поддержка нескольких языков программирования для решения задач.
  - Реализовать чат для общения между пользователями во время матчей.
  - Администратор должен иметь возможность добавлять и редактировать задачи.

non-functional:
  - Система должна обеспечивать ответное время не более 1 секунды для критически важных операций (например, выполнение задач).
  - Обеспечить доступность системы 99.9% времени в течение месяца.
  - Все данные пользователей должны быть защищены и передаваться по защищенным каналам (например, HTTPS).
  - Веб-интерфейс должен быть адаптирован для работы на мобильных устройствах.
  - Время отклика пользовательского интерфейса должно быть не более 200 миллисекунд.
  - Приложение должно поддерживать нагрузку до 1000 одновременных пользователей.
  - Система должна сохранять данные пользователей в случае сбоя и обеспечивать возможность восстановления.
  - Проект должен быть совместим с основными браузерами (Chrome, Firefox, Safari, Edge).

implicit:
  - Пользовательский интерфейс должен быть интуитивно понятным и простым в использовании.
  - Приложение должно обеспечивать корректную работу при медленном интернет-соединении.
  - Система должна поддерживать локализацию и перевод интерфейса на несколько языков.
  - Ожидается, что администраторы системы будут иметь достаточные навыки для управления и настройки платформы.
  - Код должен быть легко поддерживаемым и расширяемым для добавления новых функций в будущем.
